id: I6D1EDEE1
legacy_id: P001798
ocr_import_info:
  bdrc_scan_id: W20221
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T22:06:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:20:35.348393+00:00'
last_modified: 2022-09-01 21:20:41.364642
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W20221
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW20221
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྨ་འགྲམ་གྱི་ཚོར་སྣང་།
  author: བེ་སིའི་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7105781138546202
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1KG23278:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG23278
      total_pages: 120
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG23278.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.7105781138546202
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
